name: custom-check

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0

      - name: Run tests coverage
        run: make test-coverage
